# Problem 2: Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence 
# whose values do not exceed four million, 
# find the sum of the even-valued terms.

def fib_starter(x, y):
	sequence = []
	sequence.append(x)
	sequence.append(y)
	temp = x + y	
	
	while temp < 4000000:
		x = y
		y = temp
		temp = x + y
		sequence.append(y)

	sum = 0
	print len(sequence)
	for num in sequence:
		if num % 2 == 0:
			sum += num

	print sum


fib_starter(1, 2)	